service: GrassKeeper
frameworkVersion: '3'
useDotenv: true

params:
  default:
    region: 'ap-northeast-1'

provider:
  name: aws
  runtime: python3.9
  region: ${param:region}

functions:
  grasskeeper:
    handler: grasskeeper.handler
    environment:
      DISCORD_WEBHOOK_ID: ${env:DISCORD_WEBHOOK_ID}
      DISCORD_WEBHOOK_TOKEN: ${env:DISCORD_WEBHOOK_TOKEN}
      GITHUB_TOKEN: ${env:GITHUB_TOKEN}
      GITHUB_USERNAME: ${env:GITHUB_USERNAME}
      ENV: ${sls:stage}
    events:
      - schedule: cron(0 1,6,11 * * ? *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePoetry: true
